# Pull Official Base Image
FROM python:3.8.8-slim-buster

# Create Directory for the App User
RUN mkdir -p /home/app

# Create the App User
RUN addgroup --system app && adduser --system --group app

# Create the Appropriate Directories
ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# Set Environment Variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1
ENV ENVIRONMENT prod
ENV TESTING 0

# Install System Dependencies
RUN apt update \
    && apt -y install netcat gcc postgresql \
    && apt clean

# Install Python Dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt
RUN pip install "uvicorn[standard]==0.13.4"

# Add App
COPY . .

# CHOWN all the Files to the App User
RUN chown -R app:app $APP_HOME

# Change to the App User
USER app

## Run Gunicorn
CMD gunicorn --bind 0.0.0.0:$PORT app.main:app -k uvicorn.workers.UvicornWorker
